### ISSUE TITLE
WLan Hotspot

### ISSUE THREAD

**Issue by HirschiD** [muhamed89/MIUI#1001]
Der Name des Wlan Hotspots kann nicht geändert werden, bzw wird nach einer weile wieder auf Standard zurückgesetzt.

Redmi 3
MIUI 8 Global 6.9.8 Beta

**Comment by pareh** [comment]
Auf die Global Versionen haben wir kein Einfluss. Bitte den Fehler bei en.miui.com melden.

**Comment by HirschiD** [comment]
Welches ist "eure" ROM? Und wo bekomme ich die?

Am 21.09.2016 9:04 vorm. schrieb "pareh" <notifications@github.com>:

>

> Auf die Global Versionen haben wir kein Einfluss. Bitte den Fehler bei
en.miui.com melden.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
<https://github.com/muhamed89/MIUI/issues/1001#issuecomment-248528701>, or
mute the thread

**Comment by pareh** [comment]
es geht hier um xiaomi.eu ROMs
