### ISSUE TITLE
xml issues

### ISSUE THREAD

**Issue by ingbrzy** [muhamed89/MIUI#1002]
http://translators.xiaomi.eu/XML_MIUI8-German-de.html

**Comment by pareh** [comment]
@ingbrzy 
thank you for report. can you help me? do you know how to fix this lines?

German/main/MiuiGallery.apk/res/values-de/strings.xml
125:  <string name="aspect_ratio_format">%d:%d</string>

German/main/Music.apk/res/values-de/strings.xml
111:  <string name="comment_format">%s: %s</string>

**Comment by ingbrzy** [comment]
why you need them in translation..? they are not translatable so just remove them...
