### ISSUE TITLE
6.9.22 Nicht übersetzt + Menüabbruch

### ISSUE THREAD

**Issue by MeiGuddet** [muhamed89/MIUI#1009]
Nicht übersetzte Menüpunkte:
Einstellungen > Bildschirmsperre & Passwort >Privacy protection password
Einstellungen > Bildschirmsperre & Passwort >Launch Camera Press volume...

Menübabbruch:
Einstellungen > Bildschirmsperre & Passwort >Privacy protection password >> kein Zugriff, es führt zurück in Menü Einstellungen

Xiaomi Redmi 3 (ido)

**Comment by pareh** [comment]
Hi, danke für dein Feedback
Erster Teil ist gefixt
Sind die Menüabbrüche da, wenn man auf Englisch umstellt?

**Comment by MeiGuddet** [comment]
Ja, auch in Englisch.

**Comment by pareh** [comment]
>Ja, auch in Englisch.
Dann ist das kein Übersetzungsproblem und Xiaomi hat anscheinend da ein Bug eingebaut.

**Comment by MeiGuddet** [comment]
Habe gerade einen Bug gemeldet. Mal sehen, was draus wird :-)
