### ISSUE TITLE
App Icons bei push notification am Bildschirmrand fehlen :((

### ISSUE THREAD

**Issue by Katjamarie** [muhamed89/MIUI#1017]
Hallo, folgendes Problem:

Obwohl ich ich den Einstellungen für die Benachrichtigung auch die App-icons aktiviert habe erscheinen diese nicht oben am Bildschirmrand. Erst beim herunter ziehen kann ich sehen welche neuen Benachrichtigung es gibt. Die Rechte für Autostart habe ich auch gecheckt. Ich  hoffe es gibt eine Lösung dafür.  Danke😊☀

**Comment by berlinux2016** [comment]
kannst du mal bitte einen screenshot posten?

**Comment by Katjamarie** [comment]
![screenshot_2016-09-27-15-53-21_com miui home](https://cloud.githubusercontent.com/assets/22434575/18876642/c3ed8c3a-84ca-11e6-8739-2f7f8066db30.png)
![screenshot_2016-09-27-15-53-14_com miui home](https://cloud.githubusercontent.com/assets/22434575/18876651/cadf402e-84ca-11e6-9c83-199910787d6d.png)

**Comment by Katjamarie** [comment]
Ich kann auf dem homescreen sowie beim heruntersliden sehen dass es Neuigkeiten in den Apps gibt, es fehlen jedoch die App icons dafür ganz iben am Bildschirmrand. Normalerweise sieht man diese bereits slebst wenn der Bildschirm noch gesperrt ist.

**Comment by pareh** [comment]
Schalte bitte unter Einstellungen > Benachrichtigungen > Benachrichtigungssymbole ein.
