### ISSUE TITLE
6.9.29 / Alarm in silent mode + Battery drain

### ISSUE THREAD

**Issue by JuggedHareBoy** [muhamed89/MIUI#1018]
Hi,

still after Full Wipe or Davilk+Cache Wipe my alarm is silenced in Silence Mode, even if "Alarm in silent mode" is activated.

Additional heavy battery drain, caused by Android System.

Redmi Note 2, fresh installed 6.9.29 Miui 8.1 Beta weekly Update

**Comment by berlinux2016** [comment]
please make a full wipe. because in some cases of update it will make on the note 2 heavy battery drain.
