### ISSUE TITLE
6.9.29 Roaming in eplus/o2-Netz

### ISSUE THREAD

**Issue by ExtpumaJl** [muhamed89/MIUI#1019]
Das System melden immer, dass Roaming eingeschaltet werden soll, wenn es im o2-Netz ist. Wenn man Roaming einschaltet, wird die Internet-Geschwindigkeit sehr begrenzt, wenn es wieder im eplus-Netz ist.

**Comment by berlinux2016** [comment]
welches endgerät und welche MIUI version nutzt du?

**Comment by ExtpumaJl** [comment]
Redmi Note 4. Dev 6.9.29

**Comment by ExtpumaJl** [comment]
Richtig. Momentan findet ein Netzzusammenschluss des Eplus- und o2-Netzes statt. Vielleicht Ende Oktober besteht das Problem nicht mehr.

**Comment by berlinux2016** [comment]
Es sind momentan mehrere Probleme im O2 (Eigentümer) und eplus Netz. Also ich konnte gerade bei einem Test das Problem im Berlin Brandenburger Raum nicht reproduzieren. Also gehe davon aus-es ist kein ROM sondern ein Anbieter Problem.
