### ISSUE TITLE
add collaborator

### ISSUE THREAD

**Issue by ingbrzy** [muhamed89/MIUI#1020]
Please add @MarkH-UK as collaborator... thanks..

**Comment by berlinux2016** [comment]
done

**Comment by ingbrzy** [comment]
Are you sure..? He said no invitation sent...

**Comment by muhamed89** [comment]
Maybe 5 min. after I get mail-notification.

**Comment by ingbrzy** [comment]
did you grant him write access?

**Comment by muhamed89** [comment]
![screenshot_2016-10-12-14-47-23-063_org mozilla firefox](https://cloud.githubusercontent.com/assets/14260113/19310564/044707e0-908b-11e6-80e7-1b4971375752.png)

Look

**Comment by ingbrzy** [comment]
btw.. I see you got working VoLTE.. Which ROM version and which carrier are you using..?

**Comment by berlinux2016** [comment]
i have the last one. volte working with carrier o2/eplus germany

**Comment by ingbrzy** [comment]
and device?

**Comment by ingbrzy** [comment]
and whats are mcc and mnc in APN settings for your carrier..?

**Comment by muhamed89** [comment]
Mi5, Deutsche Telekom (1800 MHz), 8.0.12.0 stable. APN is the stock one (didnt change anything). 
![screenshot_2016-10-12-15-38-20-959_com android settings](https://cloud.githubusercontent.com/assets/14260113/19312272/f7527982-9091-11e6-863e-c1bc5168e85f.png)

**Comment by ingbrzy** [comment]
thanks.. and ROM is Global or our xiaomi.eu..?

**Comment by muhamed89** [comment]
What a question :D xiaomi.eu stable of course ;)
