### ISSUE TITLE
Lockscreen-Übersetzung bei niedrigem Akkustand

### ISSUE THREAD

**Issue by cschmatzler** [muhamed89/MIUI#1022]
Moin!
Bei unter 20% Akku wird unten im Lockscreen rot "Schließen Sie Ihr Ladegerät", sollte aber ja wahrscheinlich "Schließen Sie Ihr Ladegerät an" heißen, hat irgendwer das "an" vergessen.

**Comment by muhamed89** [comment]
Servus, ich denke das passt nicht wegen der Länge des Wortes... Werd es checken sobald ich am Rechner bin oder jemand vom Team prüft das. 

Gruß

**Comment by pareh** [comment]
Hi, könntest du bitte ein Screenshot von der Meldung schicken?

**Comment by berlinux2016** [comment]
Wenn ein Screenshot vorhanden ist, bitte wieder öffnen.
