### ISSUE TITLE
Wetter App zeigt sonnig statt klar

### ISSUE THREAD

**Issue by slikv56** [muhamed89/MIUI#1024]
Die  Wetter App zeigt anstatt der korrekten Übersetzung von "clear"  (klar)  lediglich "sonnig"  an.  Das macht gerade Nachts sehr wenig Sinn...

**Comment by berlinux2016** [comment]
Fixed

**Comment by cp82** [comment]
![screenshot_2016-10-29-20-07-50-699_com android browser](https://cloud.githubusercontent.com/assets/14348503/19831808/a252e702-9e13-11e6-9fd0-6b2e11fb1fa4.png)

Im Original steht auch sonnig 🤔

**Comment by slikv56** [comment]
Kann es sein dass es wieder geändert ist, überall steht wieder "klar"??!!

**Comment by pareh** [comment]
Was stimmt mit klar nicht? Auf Accuweather heißt es auch Klar. Vor allem abends wenn die Sonne nicht da ist, stimmt sonnig einfach nicht.

**Comment by slikv56** [comment]
Abend ist klar bzw. clear ja auch vollkommen korrekt.  Nur kann es nicht richtig sein, das es gar nicht mehr sonnig oder sunny gibt. Das ist bei Akkuweather auch anders.

**Comment by pareh** [comment]
c32046d in diesem Commit wurde von sonnig auf klar geändert, weil abends und nachts nicht richtig angezeigt wurde. 
Es kann sein dass xiaomi, dass jetzt richtig zugeordnet hat. Teste bitte was auf englisch abends angezeigt wird.

**Comment by slikv56** [comment]
Scheinbar neuerdings auch auf englisch sowohl tagsüber als auch nachts "clear"...

**Comment by slikv56** [comment]
Hier zur Verdeutlichung nochmal der Vergleich WeatherM8 (Sonnig), und Stock Weather2 App:

![miuii](https://cloud.githubusercontent.com/assets/20169240/24657414/679cf252-1946-11e7-9df6-5184a5a3d010.png)
![waetherm8](https://cloud.githubusercontent.com/assets/20169240/24657415/67c22e1e-1946-11e7-946b-9c6b961893d1.png)

**Comment by pareh** [comment]
Habe ich geändert, müsste beim nächsten Update passen.
