### ISSUE TITLE
Wetter App Überschriften falsche Position

### ISSUE THREAD

**Issue by ExtpumaJl** [muhamed89/MIUI#1026]
Die Überschriften in Wetter App unter Weitere Tage sind etwas komisch dargestellt und nicht zentriert.
![screenshot_2016-11-08-07-32-39-805_com miui weather2](https://cloud.githubusercontent.com/assets/425377/20089505/9c9afe5a-a587-11e6-8b79-21b4dd6c3b35.png)

**Comment by ExtpumaJl** [comment]
Sorry, habe auf confirm gedrückt ohne was zu beschreiben.
Die Überschriften in Wetter App unter Weitere Tage sind etwas komisch dargestellt und nicht zentriert.

**Comment by berlinux2016** [comment]
Ist mit der ROM 11.11.2016 behoben

**Comment by ExtpumaJl** [comment]
Toll. Danke.
