### ISSUE TITLE
MIUI 5.12.11 Beta auf System One 

### ISSUE THREAD

**Issue by Katjamarie** [muhamed89/MIUI#1027]
Mein Gerät hatte über Stunden einen total Absturz. Über den recovery mode habe ich schließlich "Reboot to System one" gewählt. Anschließend habe ich noch den Cache gelöscht.

Seitdem läuft aber nichts mehr wie es soll, z.B.
-die Funktionen der Tasten 'home' 'zurück'  und lässt sich auch nicht anpassen/umstellen
-Push Benachrichtigungen kommen nicht an
-Handynetz der 2. Simkarte wird nicht mehr empfangen
-usw.

Kann es sein das MIUI 5.12.11 auf dem System One nicht richtig läuft? (Ich kenne mich wirklich null aus)
Bringt es was wenn ich den ROM flashe?

**Comment by FireEmerald** [comment]
Nicht's für ungut, aber dein beschriebenes Problem hat nicht wirklich etwas mit der deutschen MIUI Übersetzung zu tun. Falls sich hier sonst niemand meldet, versuch es mal im Forum mit deiner Frage.

**Comment by berlinux2016** [comment]
FireEmerald hat das richtig geschrieben. Deshalb wird hier zu gemacht.
