### ISSUE TITLE
Benachrichtigung über voll aufgeladenen Akku

### ISSUE THREAD

**Issue by ExtpumaJl** [muhamed89/MIUI#1028]
Da fehlt ein leer-Zeichen: Akkuladezeit10 Min
Dev 6.11.10
![screenshot_2016-11-11-09-51-51-045_com miui home](https://cloud.githubusercontent.com/assets/425377/20209558/465bb12c-a7f5-11e6-8e94-d87514ed312a.png)

**Comment by cp82** [comment]
erledigt, danke

**Comment by ExtpumaJl** [comment]
Danke euch.
