### ISSUE TITLE
Sicherheitscenter / Schreibfehler

### ISSUE THREAD

**Issue by slikv56** [muhamed89/MIUI#1029]
Hier müsste es heissen : "Einige Punkte können optimiert werden."
![screenshot_2016-11-11-10-14-01-353_com miui securitycenter](https://cloud.githubusercontent.com/assets/20169240/20210096/0f27655e-a7f8-11e6-9b30-7bf73cbc1027.png)

**Comment by cp82** [comment]
erledigt, danke
