### ISSUE TITLE
Und wieder Wetter App

### ISSUE THREAD

**Issue by ExtpumaJl** [muhamed89/MIUI#1030]
Einige Mängel:
Leichter Schneefall und die Temperatur sind verschoben
![screenshot_2016-11-13-19-25-10-865_com miui weather2](https://cloud.githubusercontent.com/assets/425377/20247836/61476970-a9d7-11e6-9783-6fad2996bff5.png)
Data expired
![screenshot_2016-11-11-14-12-57-101_com miui weather2](https://cloud.githubusercontent.com/assets/425377/20247837/693ec484-a9d7-11e6-9a4e-dfb00659232b.png)
Danke.

**Comment by cp82** [comment]
Bei "leichter Schneefall" ist wohl der Text zu lang.

**Comment by FireEmerald** [comment]
- Data Expired kann ich bestätigen.
- Die Temperatur ist nicht verschoben, sondern nur das Icon bedingt durch den zweizeiligen Text.

Zwei Zeilen gibt es außerdem auch bei "Mäßiger Regen". Der Text ist dort ebenfalls links bündig, anstatt zentriert. Ergo würde ich mal behaupten sobald der Text mehr als eine Zeile hat, ist er nicht mehr zentriert.

**Comment by FireEmerald** [comment]
Btw. das selbe Verhalten lässt sich auch in anderen Apps von Xiaomi finden, wie in Mi Fit:
![img_20161114_085357](https://cloud.githubusercontent.com/assets/1107939/20257222/6134ae54-aa48-11e6-933c-570cb6167131.jpg)

**Comment by pareh** [comment]
"data expired" wurde korrigiert. Auf den zweizeiligen text haben wir kein Einfluss. Einzeilig ist es schwierig die Wörter zu übersetzen.
