### ISSUE TITLE
Schreibfehler im "Ausschalten" Bildschirm 

### ISSUE THREAD

**Issue by mzerene** [muhamed89/MIUI#1033]
Bei eingeschaltetem Wecker erscheint im Bildschirm Ausschalten die Meldung:
"Ihr Telefon wird um Morgen..." anstelle von, "Ihr Telefon wird Morgen um..."

![screenshot_2016-12-04-11-30-16-652_com miui home](https://cloud.githubusercontent.com/assets/24374884/20868723/9a88bce8-ba62-11e6-91fa-74f53e598db9.png)

**Comment by berlinux2016** [comment]
Fixed

**Comment by mzerene** [comment]
Danke!
