### ISSUE TITLE
Englische Pfade in den Einstellungen

### ISSUE THREAD

**Issue by darki15** [muhamed89/MIUI#1042]
Hi,

siehe hier:
http://www.directupload.net/file/d/4579/4fvfhfyn_png.htm

Englische Pfade; müssen die bleiben, damit das System läuft und nicht zu viel Aufwand betreiben zu müssen oder kann man das ändern?

**Comment by darki15** [comment]
?

**Comment by FireEmerald** [comment]
So wie ich das sehe fehlen die zu übersetzenden Strings komplett. Der Text `Set up portable hotspot` findet sich zum Beispiel unter ` <string name="wifi_tether_configure_ap_text">`, welcher in unserem Repository schlicht nicht vorhanden ist.

Siehe [Settings.apk/res/values/strings.xml#L3642](https://github.com/Acid-miuipolskapl/v6-XML-Compare/blame/3b6e4dd757d033089629cabaa9ea101aad8c57a8/leo/Settings.apk/res/values/strings.xml#L3642).
Bzw. [Suche nach `Set up portable hotspot` in Acid-miuipolskapl/v6-XML-Compare](https://github.com/Acid-miuipolskapl/v6-XML-Compare/search?utf8=%E2%9C%93&q=Set+up+portable+hotspot)

**Comment by cp82** [comment]
Die Pfade wurden nun größtenteils übersetzt
