### ISSUE TITLE
Remote SIM Access (rSAP) funktioniert nicht in der Version 6.12.22 beim MI5s

### ISSUE THREAD

**Issue by markzh59** [muhamed89/MIUI#1043]
Hallo! Leider lässt sich mein Phone nicht mehr mittels rSAP mit dem Autotelefon von Audi koppeln. In der Version 6.12.8 funktionierte dies noch. Habe deshalb das Update wieder deinstalliert und 6.12.8 draufgespielt. Wäre toll, wenn ihr das beim nächsten Update wieder ermöglichen könntet. Danke. Gruss Markus

**Comment by FireEmerald** [comment]
Dieses Repository und damit auch der Bugtracker sind nur für Bugs gedacht, welche mit der **deutschen Übersetzung** (Schreibfehler bzw. englische Passagen) zusammen hängen. Der Grund deines Problemes dürfte nicht an der Übersetzung liegen.

**Comment by markzh59** [comment]
Hallo! Danke für deine rasche Rückmeldung. Weißt du, wo man solche Bugs melden kann, da ich auch nicht davon ausgehe, dass die Übersetzung die Ursache ist.

**Comment by FireEmerald** [comment]
@markzh59 https://xiaomi.eu/community/forums/bugs.20/
