### ISSUE TITLE
MiKalender unvollständig übersetzt

### ISSUE THREAD

**Issue by EdlerProgrammierer** [muhamed89/MIUI#1046]
[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)

Wenn man nen neuen Termin erstellt, ist birthday gar nicht übersetzt.

**Comment by EdlerProgrammierer** [comment]
test

**Comment by cp82** [comment]
Wurde mit 7.1.5 behoben
