### ISSUE TITLE
Falsche deutsche Übersetztung

### ISSUE THREAD

**Issue by MeiGuddet** [muhamed89/MIUI#1047]
Menü Uhr > Weitere Einstellungen > Automatische Stummschaltung: Alarme werden nach 10 Minuten stumm "geschalten" >> Es muss heißen "**geschaltet**"

**Comment by MeiGuddet** [comment]
Danke, pareh. 
      In dem korrigierten Bereich ist mir gerade noch was aufgefallen:
      German/main/CloudService.apk/res/values-de/strings.xml
      
      Zeile 84  <string
        name="find_device_disabled_notice">"Sie können diese Funtion jederzeit in den Mi Cloud
        Einstellungen ein- oder ausschalten."</string>
        Hier fehlt ein 'k'
        
        Gruß, Ira
      
      
      
        
          ••• Originalnachricht •••
        Gesendet:  Sonntag, 8. Januar 2017 12:59:08
        Von: Pareh
        An: Muhamed89/miui
        CC: Prieß Ira_gmail, Author
        Betreff: Re: [muhamed89/MIUI] Falsche deutsche
        Übersetztung (#1047)
      Closed #1047
        via fcfaa73.
    
    
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/muhamed89/MIUI","title":"muhamed89/MIUI","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/muhamed89/MIUI"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #1047 via fcfaa73c318578483f8fb0a404ddb279c9910b1a."}],"action":{"name":"View Issue","url":"https://github.com/muhamed89/MIUI/issues/1047#event-915207129"}}}

**Comment by cp82** [comment]
Ist korrigiert, danke!
