### ISSUE TITLE
MiKalender Einstellungen

### ISSUE THREAD

**Issue by EdlerProgrammierer** [muhamed89/MIUI#1048]
[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)

**Comment by EdlerProgrammierer** [comment]
MiKalender -> Einstellungen
Da steht default all day reminder time

**Comment by cp82** [comment]
Erledigt, danke!
https://github.com/muhamed89/MIUI/commit/bd4feb45c4d4c6318620162ef5c44e38ddfbced9
