### ISSUE TITLE
Fingerprint Einstellungen

### ISSUE THREAD

**Issue by darki15** [muhamed89/MIUI#1051]
Fingerprint Einstellungen
Vor "Passwort vergessen" steht:
<u>

Vielleicht Code nicht geschlossen mit </u>?

**Comment by pareh** [comment]
Hi, danke für dein Feedback. 
Könntest du bitte ein Screenshot davon schicken und die Version vom Smartphone und MIUI angeben?

**Comment by Henry2o1o** [comment]
![photo_2017-01-14_15-45-01](https://cloud.githubusercontent.com/assets/6131799/21955689/7484b41a-da70-11e6-8591-4c7079639afc.jpg)
