### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by Henry2o1o** [muhamed89/MIUI#1052]
![photo_2017-01-14_15-47-01](https://cloud.githubusercontent.com/assets/6131799/21955728/081da290-da71-11e6-875d-050ef55d748f.jpg)

![photo_2017-01-14_15-52-01](https://cloud.githubusercontent.com/assets/6131799/21955749/82037512-da71-11e6-9450-b8f22039f7ea.jpg)

**Comment by pareh** [comment]
Fixed 3dfb93d
