### ISSUE TITLE
Komische Sonderzeichen etc.

### ISSUE THREAD

**Issue by maschhoff** [muhamed89/MIUI#1054]
[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)
Hey, in der aktuellen Version bekomme ich komische Sonderzeichen wie <p Passwort zurücksetzen / oder < U§berspringen /)( weiß nicht ob das wirklich an der Übersetzung oder an der ROM liegt aber ist komisch.

**Comment by pareh** [comment]
Danke für dein Feedback.
Wurde bereits behoben 3dfb93d1cc39162ff58439dd27ef347b94172d2a

**Comment by Henry2o1o** [comment]
original
<u>Forgot password</u>

<u>忘记密码</u>

in der 7.1.5

<u>Passwort vergessen</u>

**Comment by pareh** [comment]
Ja in diesem commit wurden die ganzen Formatierungszeichen geändert fcf21ef3ee7ba58f2e017d45f400e09677895fb5
Wir müssen schauen was alles noch zurückgeändert werden muss
Ich öffne Issue wieder

**Comment by pareh** [comment]
Die Zeichen müssten mit dem nächsten Update weg sein. Danke für die Meldungen.
