### ISSUE TITLE
Chinesische Zeichen im Menü Bedienungshilfen

### ISSUE THREAD

**Issue by MeiGuddet** [muhamed89/MIUI#1060]
[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)
Weitere Einstellungen > Bedienungshilfen > Sicherheit > Hier sind chinesische Zeichen vorhanden.

**Comment by berlinux2016** [comment]
Das Problem kann noch nicht behoben werden, da der String noch nicht von Xiaomi eingepflegt wurde. Sobald der drin ist ändern wir das ab.

**Comment by malchik-solnce** [comment]
<string name="accessibility_service_description">"开启此功能，即可进行QQ群红包提醒。
提示：小米红包助手不会通过辅助功能收集用户任何隐私，请放心开启！"</string>

**Comment by malchik-solnce** [comment]
`<string name="accessibility_service_description">"开启此功能，即可进行QQ群红包提醒。
提示：小米红包助手不会通过辅助功能收集用户任何隐私，请放心开启！"</string>`
