### ISSUE TITLE
Statuszeile vom Hotspot ist englisch

### ISSUE THREAD

**Issue by Fredddddd** [muhamed89/MIUI#1061]
Seit 2 Versionen ist die Statuszeile des (aktiven) Hotspots Englisch statt Deutsch. 

[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)

**Comment by pareh** [comment]
Hi, schicke bitte ein Screenshot davon

**Comment by Fredddddd** [comment]
Wie geht das? Wenn. Ich die statusleiste runterziehe kann ich nicht ein Screenshot von der Statuszeile machen oder?

**Comment by pareh** [comment]
Vol down + Power

**Comment by Fredddddd** [comment]
![img_20170225_113729](https://cloud.githubusercontent.com/assets/26022699/23330473/f4f03292-fb4e-11e6-87f6-c71935a5c40d.jpg)

**Comment by Fredddddd** [comment]
?

**Comment by pareh** [comment]
Wird beim nächsten Update korrigiert

**Comment by Fredddddd** [comment]
Top! :-)
