### ISSUE TITLE
7.2.23 Mailboxeinstellungen

### ISSUE THREAD

**Issue by slikv56** [muhamed89/MIUI#1064]
Bei Mailboxdienst steht "Your carrier"

**Comment by pareh** [comment]
Screenshot?

**Comment by slikv56** [comment]
![screenshot_2017-03-06-09-45-04-379_com android phone](https://cloud.githubusercontent.com/assets/20169240/23602647/b75a41e8-0251-11e7-983a-8d35d2ed607e.png)
