### ISSUE TITLE
Galerie neue Fotos

### ISSUE THREAD

**Issue by n0w4y** [muhamed89/MIUI#1070]
In der Galerie steht bei neuen Bildern ganz oben "found new photos".

**Comment by pareh** [comment]
Bitte Schreenshot einfügen

**Comment by n0w4y** [comment]
![img_20170313_135038](https://cloud.githubusercontent.com/assets/26310479/23855014/59d96dd4-07f4-11e7-869f-489f49ff3c34.jpg)
