### ISSUE TITLE
SIM-Verwaltung

### ISSUE THREAD

**Issue by n0w4y** [muhamed89/MIUI#1074]
Unter Einstellungen - SIM-Verwaltung steht bei der Auswahl, welche SIM-Karte für Telefonie und welche für Daten verwendet werden soll "Default settings". Sollte "Standardeinstellung" lauten.

![img_20170314_134606](https://cloud.githubusercontent.com/assets/26310479/23901284/d59f96fa-08bc-11e7-8f6b-81fbd6adbcad.jpg)

**Comment by pareh** [comment]
fixed hier 635a95e6105267df85f6ffcff966646e67faf388
