### ISSUE TITLE
Uhrenwidget Acid

### ISSUE THREAD

**Issue by n0w4y** [muhamed89/MIUI#1077]
Beim 4x2 Uhrenwidget mit Luftfeuchtigkeitsanzeige steht "Humidity" statt "Luftfeuchtigkeit", beim Tagesdatum fehlt ein Punkt und vor der Windgeschwindigkeit fehlt, wie auch bei der Temperatur, ein Leerzeichen.

Bin mir aber nicht sicher, ob ihr auf die Strings Zugriff habt, da das Widget von Acid/MIUI.cz ist.

![img_20170316_200556](https://cloud.githubusercontent.com/assets/26310479/24014274/94b454ae-0a84-11e7-997f-6a84e76929bd.jpg)
![img_20170316_200311](https://cloud.githubusercontent.com/assets/26310479/24014297/ac18c2b0-0a84-11e7-8b7b-d727ab6982ea.jpg)

**Comment by pareh** [comment]
Das sind Themenstrings. Das können wir hier nicht anpassen.
