### ISSUE TITLE
STILL CHINESE CHARACTERS

### ISSUE THREAD

**Issue by dburger1974** [muhamed89/MIUI#1085]
Hello Community,

I have a MI5 and run 7.3.16 Beta (MIUI8.3). I just updated today to see if the chinese characers have been updated.

I have Chinese characters on my lockscreen for the date below the time.
Also there is a Settings symbol right top corner of my lockscreen which when I open it, the entire
menue is still chinese.

looking for a fix.

Thanks in advance

Daniel

**Comment by ingbrzy** [comment]
Uninstall update of Wallpaper carousel app..

**Comment by berlinux2016** [comment]
Fixed
