### ISSUE TITLE
"No Service" statt "Kein Dienst"

### ISSUE THREAD

**Issue by EdlerProgrammierer** [muhamed89/MIUI#1086]
[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)
Wenn man aus dem Flugzeugmodus wechselt, dann steht oben in der Leiste kurz "No service" statt "Kein Dienst" auf Deutsch.

**Comment by berlinux2016** [comment]
Fixed
