### ISSUE TITLE
Fehlende Übersetzung / Falscher link

### ISSUE THREAD

**Issue by mzerene** [muhamed89/MIUI#1094]
Wenn mann im miui Browser auf eine der beiden Google Suchleisten tippt, erscheinen vier Felder mit Chinesischen Schriftzeichen, die beim antippen auf verschiedene Chinesische Seiten verweisen.
![screenshot_2017-04-09-00-59-51-902_com android browser](https://cloud.githubusercontent.com/assets/24374884/24833136/4fde9c06-1cc0-11e7-8544-b71e52cdbfcd.png)

**Comment by berlinux2016** [comment]
Sorry das können wir mit den Übersetzungsfiles nicht beheben.

**Comment by mzerene** [comment]
Trotzdem Danke!

**Comment by cp82** [comment]
Du musst nur in den Einstellungen der Suche die Funktion "Top Search" ausschalten.
Dann sind die chinesischen Vorschläge weg.
