### ISSUE TITLE
Fehlende Übersetzung im Menüpunkt "Farben & Kontrast"

### ISSUE THREAD

**Issue by mzerene** [muhamed89/MIUI#1095]
Unter der Auswahl "Erhöhter Kontrast", steht Bilschirmkontrast verringern, wo aber Bildschirmkontrast ERHÖHEN stehen sollte.
![screenshot_2017-04-22-15-05-15-583_com android settings](https://cloud.githubusercontent.com/assets/24374884/25304888/b0d19620-2770-11e7-9176-ac1b91bdbc9f.png)

**Comment by berlinux2016** [comment]
fixed

**Comment by mzerene** [comment]
Vielen Dank!
