### ISSUE TITLE
Update MI 5

### ISSUE THREAD

**Issue by wirthh** [muhamed89/MIUI#1098]
I am fighting since months with the update for my MI 5.
Either I get the answer No Update Available, Can Not Verify, Server couod be connected or turn WLAN on (even it is on) if I use the Updater. I tried it already with all opportunities but still does not work!
Here is the most failure of my MiFlash: 
[0.00  fbfd9b1c]:can not found file flash_all.bat.Other Log Files I attached.
[MiFlash-Result@201759.txt](https://github.com/muhamed89/MIUI/files/997221/MiFlash-Result.201759.txt)

My latest Android security patch level is 2016-02-01; MIUI Version:MIUI Global 7.2.8.0 (MAACNDB) Stable.
Do you have any solution to fix this problem? Any advice I did not do so far?
Regards,
Hans Wirth

wirthh@web.de
[fbfd9b1c@201759072.txt](https://github.com/muhamed89/MIUI/files/997215/fbfd9b1c.201759072.txt)
[miflash@201754.txt](https://github.com/muhamed89/MIUI/files/997216/miflash.201754.txt)
[MiFlash-Result@2017424.txt](https://github.com/muhamed89/MIUI/files/997217/MiFlash-Result.2017424.txt)

**Comment by FireEmerald** [comment]
Hi @wirthh, your problem isn't related to the german translation.

**This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.**

This means a misspelled word or english phrases which aren't translated yet into german.
For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/
