### ISSUE TITLE
Appsperre deaktivieren

### ISSUE THREAD

**Issue by n0w4y** [muhamed89/MIUI#1101]
Beim Deaktivieren der Appsperre fehlt die deutsche Übersetzung des Hinweisdialogs:

![screenshot_2017-05-30-10-14-34-493_com miui securitycenter](https://cloud.githubusercontent.com/assets/26310479/26574332/3cae43f0-4521-11e7-9be8-8c961fbc9f41.png)

**Comment by berlinux2016** [comment]
fixed
