### ISSUE TITLE
Web Apps 

### ISSUE THREAD

**Issue by Sedumjo** [muhamed89/MIUI#1103]
Bei dem Menü Einstellungen - > Weitere Einstellungen - > Sicherheit 
ist ganz unten der Punkt "Web app" 
Vielleicht lieber zusammenschreiben oder das "a" in groß schreiben?
In diesem Menüpunkt steht:
"Web app
Open apps faster without installing them"

Ihr leistet übrigens super Arbeit. Vielen Dank dafür.

**Comment by berlinux2016** [comment]
fixed
