### ISSUE TITLE
Berührungsassistent - Einstellungen 

### ISSUE THREAD

**Issue by Sedumjo** [muhamed89/MIUI#1104]
Bei dem Menüpunkt Einstellungen -> Weitere Einstellungen -> Berührungsassistent
steht ganz unten:
"ANDERE" Hier vielleicht nur den ersten Buchstaben groß? 
Darunter steht 
"Restore defaults"
Vielleicht mit "Einstellungen zurücksetzen" oder so übersetzen?

**Comment by berlinux2016** [comment]
Die Großschreibung gibt MIUI vor kann nicht geändert werden. Ansonsten fixed.
