### ISSUE TITLE
MI Cloud Benachrichtigung 

### ISSUE THREAD

**Issue by Sedumjo** [muhamed89/MIUI#1105]
Ich bin mir nicht sicher, ob darauf Zugriff besteht... 
Von MI Cloud wird manchmal eine Benachrichtigung angezeigt:
"You have unsynced items
Details"

![mi cloud](https://cloud.githubusercontent.com/assets/29120378/26757593/6306fd50-48c1-11e7-82b0-570249ffa41d.jpg)

**Comment by berlinux2016** [comment]
fixed
