### ISSUE TITLE
Benachrichtigung Zertifikat 

### ISSUE THREAD

**Issue by Sedumjo** [muhamed89/MIUI#1106]
Nach dem Aktualisieren auf Android 7 erscheint beim ersten Mal die Benachrichtigung:
"Certificat authority installed
Von einem unbekannten Dritten" 

Und nach einem Anklicke die Einblendung:
"Trust or remove certificate
Dritte können ihre Netzwerkaktivitäten überwachen, einschließlich den E-Mails, Apps und sicheren Websites. 
Dies wird durch vertrauenswürdige Anneldedaten ermöglicht, die auf ihrem Gerät installiert sind." 
Mit den Buttons:
"Abbrechen" und "Check certificat" 
Hier vielleicht die Überschrift, Websites und den rechten Button noch übersetzen. 

Ein ganz dickes Lob noch für die tollen und vor allem schnellen Übersetzungen. Auch das Bearbeiten der Anregungen ist sehr gut :)

**Comment by wirthh** [comment]
Was heißt beim ersten Mal? Sollte ich diese Message schon einmal 
bekommen haben? Oder gibt es noch kein neues Update? Bis jetzt habe ich 
noch nichts bekommen. Ich checke von Zeit zu Zeit mit dem Update Tool ob 
eine neue Version da ist. Bis jetzt nur "keine neuen Updates".

Gruß

Hans


Am 10.Jun.17 um 13:11 schrieb Sedumjo:

**Comment by Sedumjo** [comment]
Hallo Hans,

das habe ich wohl unglücklich formuliert.

Von der Uni mussten wir ein bestimmtes Zertifikat installieren, um VPN zu 
benutzen.
Aufgrund der Installation dieses Zertifikats wird diese 
Zertifikatsbenachrichtigung angezeigt. Die Benachrichtigung erscheint aber 
nur beim ersten Starten des Smartphones. In diesem Fall direkt nach dem 
Update von Android 6 auf Android 7. Wenn man das Smartphone später neu 
startet, erscheint die Benachrichtigung nicht mehr.
Ich wollte damit zum Ausdruck bringen, dass es nicht bei jedem Start 
angezeigt wird, für den Fall, dass du die Benachrichtigung mit deinem 
Smartphone reproduzieren möchtest.

Vielleicht hätte ich es einfach weglassen sollen.

Wenn du weitere Rückfragen hast, einfach melden.

Viele Grüße,
Jens


Am 10. Juni 2017 5:27:15 nachm. schrieb wirthh <notifications@github.com>:

**Comment by wirthh** [comment]
OK Jens, soweit habe ich es verstanden.

Ich weiß nur nicht wie ich ein neues Update zu installieren habe, bzw. 
wie ich sehe, daß ein neues Update zu Verfügung steht.

a.) Kommt das Update automatisch?
b.) muß ich das mit der Update Funktion des Phones suchen und installieren?
c.)muß ich es über das XiaoMiFlash tun
d.) muß ich es über den Xiomi MiPCSuite installieren? (bekomme keine 
Verbindung zum PCSuite - andere Baustelle)

Ich würde gerne mal autark so ein Update zustande bekommen, deßhalb 
bräuchte ich noch Deine Hilfe, bis ich all diese kleinen Problem mal 
selbst lösen kann.

Vielen Dank für Deinen Einsatz mir diese Problemlösungen zu zeigen.
Gruß
Hans

Am 10.Jun.17 um 19:36 schrieb Sedumjo:

**Comment by FireEmerald** [comment]
Nutzt bitte den Bugtracker zum melden von Fehlern welche die deutsche Übersetzung von MIUI betreffen.

@wirthh In diesem Bugreport geht es um die englischen Phrasen aus dem 1. Beitrag - was deine Fragen betrifft:

>a.) Kommt das Update automatisch?

Automatische Updates oder auch "Over the air updates (OTA)" genannt, wurden seit einiger Zeit **komplett eingestellt**. Ergo wirst du lange warten können ;) Siehe [Forum Thread](https://xiaomi.eu/community/threads/7-6-8.40358/), "_Some facts about OTA delay._".

> b.) muß ich das mit der Update Funktion des Phones suchen und installieren?

Du wirst über die _Update Funktion_ deines Handys keinen neuen Updates mehr finden, da sich eben über diese Funktion nur OTA Updates finden lassen, welche es nicht mehr gibt.

> c.) muss ich es über das XiaoMiFlash tun
> d.) muss ich es über den Xiomi MiPCSuite installieren?

Weder noch, das einfachste ist, [du suchst dir deine gewünschte Version im Forum](https://xiaomi.eu/community/forums/miui-weekly-rom-releases.103/), lädst dir dort die passende ROM für dein Handy runter und installierst Sie auf deinem Endgerät mittels der MIUI Updater App.

**Updater** App -> Menübutton rechts oben -> Von SD-Karte installieren -> *.zip Datei (ROM) auswählen.

![updater](https://user-images.githubusercontent.com/1107939/27010771-e8d44eb0-4eac-11e7-9e27-d5ff4081b536.png)

**Comment by wirthh** [comment]
OK. Ich habe nun mein Update nach dieser Anweisung gemacht. Es folgte eine Fehlermeldung die im Anhang zu sehen ist 
ZIP Verification failed! 
Error installing ZIP file '@\cache\recovery\block.map
Zip file is corrupt!
Error installing ZIP file '\sdcard\download\xiaomi.eu_multi_MI5_V7.6.8-7.0zip'

Was ist da falsch gelaufen? Habe es 2mal versucht mit dem selben Erfolg - kein Update
Habe versucht einen Fehlerbericht via meinem MI5 zu senden, um diesen Fehler einzureichen - ging auch nicht

**Comment by wirthh** [comment]
Jens ich habe Dir mal den Screenshot anghängt. Sagt er Dir etwas?

Hane es nur mit dem "TWRP Install" gemacht.

Gruß

Hans



Am 10.Jun.17 um 19:36 schrieb Sedumjo:

**Comment by Sedumjo** [comment]
wirthh, ich kann dir bei dem Update nicht wirklich helfen.
Sobald die Benachrichtigung zu Zertifikaten übersetzt ist, kann das Thema geschlossen werden.

**Comment by berlinux2016** [comment]
das können wir momentan nicht übersetzen. liegt an google. deshalb closed
