### ISSUE TITLE
Miui 8.6 unsaubere Übersetzung 

### ISSUE THREAD

**Issue by Didelda** [muhamed89/MIUI#1107]
[//]: # (This Repository and it's bugtracker are ONLY intended for issues which are RELATED TO THE GERMAN TRANSLATION.)
[//]: # (This means a misspelled word or english phrases which aren't translated yet into german.)
[//]: # (For all other bugs, please use the forum under: https://xiaomi.eu/community/forums/bugs.20/)

Wenn man ein Foto unmittelbar nach der Aufnahme aus der Kamera-App löscht, kommt die Meldung:
"Dieses Foto from this device and Mi Cloud löschen?"

**Comment by berlinux2016** [comment]
fixed
