### ISSUE TITLE
Schreibfehler 7.6.15

### ISSUE THREAD

**Issue by Jamodd** [muhamed89/MIUI#1108]
Einstellungen-> alle Apps -> Xiaomi Aktivierugsservice für Simkarten
Tool Bildschirmaufnahme->Einstellungen-> Bildschirmfrequenz
"Eine höhere Bildschirmfrequenz verrigngert.."
Tool Bildschirmaufnahme->Einstellungen->Tonquelle
"Systemtöne oder Mikrifon"

**Comment by berlinux2016** [comment]
Danke & Fixed
