### ISSUE TITLE
Update MI5 via Updater & TRWP

### ISSUE THREAD

**Issue by wirthh** [muhamed89/MIUI#1109]
I still have the problem to update my MI5. I tried it the way you told me lately, but I always get the message of an corrupted ZIP file.
Could you help me, that I am able to get familiar with the update procedure for the future?
I did:
1. Downloaded the ZIP file from the EU to my PC (xiaomi.eu_MI5_7.6.8_v8-7.0.zip)
2. used the MI5 Updater :"Von SD-Karte installieren"
3. Reboot it
4. Choosed the install option (did not know if I should use the swipe too)
4. Get the message: 
"ZIP signature verification failed! Error installing zip file '@/cache/recovery/block.map"
and
Zip file is corrupt! Error installing zip file "'sdcard/Download/xiaomi.eu_MI5_7.6.8_v8-7.0.zip"

I did this two times and always happened the same Error.
What is wrong or what did I do wrong?

My current version is MIUI 8.3 by xiaomi.eu 7.5.25 Beta.
Regards
Hans

**Comment by ingbrzy** [comment]
reboot to TWRP and install it from there.. (download zip again)

its not translation issue

**Comment by wirthh** [comment]
That's exactly I did and get the mentioned Error Message. I tried to install it with the TWRP! Still does not work. My current Update Option is set to autmatically, could this an issue?
