### ISSUE TITLE
Fehlende Übersetzung in der Nachrichten/SMS-App

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1110]
In der aktuellen beta-xiaomi.eu-Version für das Mi5s vom 22.06.2017 fehlt in der Nachrichten/SMS-App die Übersetzung oben in der Suchleiste von "messages" und außerdem in der Kategorisierung der Nachrichten ("today", "yesterday", "earlier"). 

Vielen Dank!

**Comment by FireEmerald** [comment]
Wenn du bei Bugreports einen Screenshot mit in rein packst, brauchst du nicht so viel schreiben bzw. ist es auch eindeutig ersichtlich was du meinst und wie es aktuell aussieht ;) Nur für die Zukunft.

**Comment by Heinzerunzel** [comment]
![img_20170623_075529](https://user-images.githubusercontent.com/29648253/27468338-923f799e-57e9-11e7-8d67-9e04ebcf94d9.jpg)

Auf die Idee bin ich gar nicht gekommen, stimmt. Werde ich mir merken!

**Comment by berlinux2016** [comment]
Danke & fixed
