### ISSUE TITLE
Fehlende Übersetzung, WLAN-Einstellungen

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1111]
![img_20170623_074904](https://user-images.githubusercontent.com/29648253/27468231-f0b5bba6-57e8-11e7-8cd6-772409748a2d.jpg)
![img_20170623_074936](https://user-images.githubusercontent.com/29648253/27468232-f0d1b018-57e8-11e7-9edd-8aaf25fa808a.jpg)

Fehlende Übersetzung bei Einstellungen/WLAN von "Intelligent traffic strategy" und den zugehörigen Optionen "close", "normal mode" und "extreme mode".

**Comment by berlinux2016** [comment]
danke & fixed
