### ISSUE TITLE
Fehlende Übersetzung, Datenverbrauch

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1112]
![screenshot_2017-06-23-07-48-19-924_com miui securitycenter](https://user-images.githubusercontent.com/29648253/27468250-0b30d93e-57e9-11e7-9230-ff116a5d0c05.png)
Wenn man die Statusleiste herunterzieht und auf die verbrauchten mobilen Daten tippt, heißt die Statistik (ganz unten)  "Data usage stats".

**Comment by berlinux2016** [comment]
Danke & Fixed
