### ISSUE TITLE
Text-in-Sprache-Ausgabe

### ISSUE THREAD

**Issue by Sedumjo** [muhamed89/MIUI#1114]
Fehlende Übersetzung von
- Reset speech rate
    Reset the speed at which the text is spoken to normal.
- Reset speech pitch
    Reset the pitch at which the text is spoken do default.

![text-in-sprache-ausgabe](https://user-images.githubusercontent.com/29120378/27535128-c888fcaa-5a69-11e7-8656-6fcf3a4709c5.jpg)

**Comment by berlinux2016** [comment]
Danke & fixed
