### ISSUE TITLE
Keyboard Übersetzung

### ISSUE THREAD

**Issue by Sedumjo** [muhamed89/MIUI#1115]
Im Bereich Weitere Einstellungen -> Sprache & Eingabe ist der Bereich "keyboard" noch nicht übersetzt:
- virtual kayboard
- physical kayboard

![keyboard](https://user-images.githubusercontent.com/29120378/27535360-d47c4b9c-5a6a-11e7-9cbe-342fb79be26f.jpg)

**Comment by berlinux2016** [comment]
Danke & fixed
