### ISSUE TITLE
Übersetzung Galerie

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1116]
![img_20170630_093424](https://user-images.githubusercontent.com/29648253/27731693-64ecbf1a-5d8e-11e7-8b8e-339d34153ad9.jpg)

Today / Yesterday / Earlier nicht übersetzt

**Comment by berlinux2016** [comment]
Welche Version?

**Comment by Heinzerunzel** [comment]
Galerie Version 2.0.0
MIUI 8.6 by xiaomi.eu 7.6.29 beta

**Comment by berlinux2016** [comment]
Danke & Fixed
