### ISSUE TITLE
Rechtschreibfehler, IP-Adresse erhalten

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1117]
![img_20170701_094029](https://user-images.githubusercontent.com/29648253/27760190-b57d73a8-5e41-11e7-9fdf-e1c45e6d2f21.jpg)

Beim Verbinden mit einem Netzwerk "IP-Adresse erhaltens"

**Comment by berlinux2016** [comment]
Danke & fixed
