### ISSUE TITLE
Fehlende Übersetzung, Kamera-Einstellungen 

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1118]
![screenshot_2017-07-01-19-45-46-389_com android camera](https://user-images.githubusercontent.com/29648253/27766593-96bc486a-5ed5-11e7-899f-5194304ef6cc.png)

"Age & gender" in Kamera-Einstellungen nicht übersetzt

**Comment by berlinux2016** [comment]
Danke & fixed
