### ISSUE TITLE
Browser > Privatsphäre & Sicherheit

### ISSUE THREAD

**Issue by FireEmerald** [muhamed89/MIUI#1120]
![screenshot_2017-07-02-10-49-10-220_com android browser](https://user-images.githubusercontent.com/1107939/27768446-38fda824-5f14-11e7-9927-adb8e6d74e6d.png)

Browser > Einstellungen > Privatsphäre & Sicherheit
MiNote Pro 7.6.29

**Comment by berlinux2016** [comment]
Fixed & merci
