### ISSUE TITLE
Übersetzung in Notizen, Import von Bildern

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1121]
![screenshot](https://user-images.githubusercontent.com/29648253/27770302-6e6780fc-5f3c-11e7-9011-5021fc4b59a0.jpg)

Mi5S 7.6.29

**Comment by berlinux2016** [comment]
lasse es noch offen bitte mit der nächsten Version testen da es hier ein Problem gibt mit FileExplorer.apk.

**Comment by berlinux2016** [comment]
Problem wird morgen behoben. Danke
