### ISSUE TITLE
Kontakte, Standard setzen

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1122]
![img_20170702_163032](https://user-images.githubusercontent.com/29648253/27771063-d3b1660c-5f47-11e7-91b5-12d09b90a9dd.jpg)

Bei Kontakten mit mehreren Nummern keine Übersetzung beim Setzen einer Standardrufnummer. 

Mi5S 7.6.29

**Comment by berlinux2016** [comment]
Fixed & danke
