### ISSUE TITLE
Einstellungen Kontakte

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1126]
![screenshot_2017-07-03-00-11-48-454_com android contacts](https://user-images.githubusercontent.com/29648253/27783571-03458706-5fd7-11e7-80de-f17108392717.png)

Einstellungen > Systemanwendungen > Kontakte

"Show the YellowPage tab" nicht übersetzt 

Mi5S 7.6.29

**Comment by berlinux2016** [comment]
fixed & danke
