### ISSUE TITLE
Einstellungen SMS

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1127]
![screenshot_2017-07-03-00-11-03-337_com android mms](https://user-images.githubusercontent.com/29648253/27783943-85408a3e-5fd8-11e7-9c84-e5d373583cff.png)

Einstellungen > Systemanwendungen > SMS

"Use GSM alphabet" nicht übersetzt

Mi5S 7.6.29

**Comment by berlinux2016** [comment]
fixed & danke
