### ISSUE TITLE
Kalender

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1128]
![screenshot_2017-07-05-00-02-19-108_com android calendar](https://user-images.githubusercontent.com/29648253/27843656-7eeb78c6-6116-11e7-939b-3ee2b1edf8df.png)
![screenshot_2017-07-05-00-02-36-777_com android calendar](https://user-images.githubusercontent.com/29648253/27843657-7eee8584-6116-11e7-83c7-434c20194ddd.png)

Kalender > Einstellungen
"Reminders" nicht übersetzt

& Wochentage in Monatsübersicht nicht auf Deutsch abgekürzt (MON, TUE, WED usw.)

Mi5S 7.6.29

**Comment by berlinux2016** [comment]
danke & fixed
