### ISSUE TITLE
Browser, Einstellungen und Nutzungsbedingungen

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1129]
![screenshot_2017-07-05-00-03-31-459_com android browser](https://user-images.githubusercontent.com/29648253/27843709-0d441de4-6117-11e7-883b-04de28a22997.png)
![screenshot_2017-07-05-00-04-06-195_com android browser](https://user-images.githubusercontent.com/29648253/27843710-0d44dc52-6117-11e7-97a4-85cab78e1327.png)

beim Starten des Browsers Zustimmen von nicht übersetzten Nutzungsbedingungen

und  in Einstellungen > Privatsphäre & Sicherheit letzter Punkt "Get the URL" nicht übersetzt

Mi5S 7.6.29

**Comment by berlinux2016** [comment]
fixed & danke
