### ISSUE TITLE
Synchronisierung

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1131]
![screenshot_2017-07-06-00-54-09-947_com android settings](https://user-images.githubusercontent.com/29648253/27888365-e21530f2-61e5-11e7-9c7e-02e0a0af3928.png)

Einstellungen > Synchronisierung > Auto-Synchronisation einschalten
Frage nicht übersetzt 

Mi5s 7.6.29

**Comment by berlinux2016** [comment]
fixed & danke

**Comment by Heinzerunzel** [comment]
![screenshot_2017-07-07-10-02-02-712_com android settings](https://user-images.githubusercontent.com/29648253/27948883-bcfd0148-62fb-11e7-924f-f03be34e6fc5.png)

"Inhalte" sind klein geschrieben

Mi5S 7.7.6
