### ISSUE TITLE
Entwickleroptionen

### ISSUE THREAD

**Issue by wirthh** [muhamed89/MIUI#1132]
Entwickleroptionen in MIUI 8.6 Version 7.6.29 Beta.
I accidentally tried to use an obviously wrong size in the "Speicheroptimierung. After this my Entwickleroption is not functioning anymore, either the Fingersensor is not working. How can I fix this error function? Is there an option via TWRP Backup?
Ich habe versucht eine andere Einstellung in der Speicheroptimierung zu wählen, die wohl die Funktion der Entwickleroption abstürzen ließ. Jetzt funktioniert diese Option nicht mehr und der Fingersensor funktioniert somit auch nicht mehr. Ich habe den Fehlerbericht weitergeleitet wie im Abbruchfenster beschrieben.
Wie kann ich diesen Fehler wieder Rückgänging machen.
MfG
Hans
*************************************************************************************************)
(* Please fill in the fields below: *) --->
- **MIUI Version:* MIUI 8.6 Version 7.6.29 Beta
- **Device name:** Mi 5
![screenshot_2017-07-04-13-57-54-348_com android settings](https://user-images.githubusercontent.com/16719026/27920187-19eccec0-6274-11e7-97ae-172cb84541b8.png)
![screenshot_2017-07-04-14-00-19-502_com miui bugreport](https://user-images.githubusercontent.com/16719026/27920186-19eaaafa-6274-11e7-99c7-10a47dfcf55f.png)

**Screenshot:**

**Comment by berlinux2016** [comment]
Dies ist kein Fehler für die Übersetzungen deshalb closed. 

Denke du musst dein System neu zurück setzen.

**Comment by wirthh** [comment]
OK, aber was genau muss ich da tun? Kenne ja nur das Zurücksetzen in den Werkszustand. Muß ich dies tun? Sorry aber ich bin wirklich total neu auf diesem Gebiet.

**Comment by wirthh** [comment]
OK, aber was genau muss ich da tun? Kenne ja nur das Zurücksetzen in den Werkszustand. Muß ich dies tun? Sorry aber ich bin wirklich total neu auf diesem Gebiet.

Outlook for Android<https://aka.ms/ghei36> herunterladen




On Thu, Jul 6, 2017 at 7:41 PM +0200, "BerLinuX" <notifications@github.com<mailto:notifications@github.com>> wrote:


Dies ist kein Fehler für die Übersetzungen deshalb closed.

Denke du musst dein System neu zurück setzen.
