### ISSUE TITLE
Einstellungen, Synchronisierung

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1135]
![27948883-bcfd0148-62fb-11e7-924f-f03be34e6fc5](https://user-images.githubusercontent.com/29648253/27949660-c46dd288-62fe-11e7-9a15-b13f1aefdfc9.png)

"Inhalte" sind klein geschrieben

Mi5S 7.7.6

**Comment by berlinux2016** [comment]
danke & fixed
