### ISSUE TITLE
Einstellungen SMS

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1137]
![screenshot_2017-07-17-15-11-10-937_com android mms](https://user-images.githubusercontent.com/29648253/28269439-64456dd8-6b02-11e7-9ba2-f9812dd90e7b.png)

Einstellungen > Systemanwendungen > SMS
"Assign contact photos" nicht übersetzt

Mi5S 7.7.13

**Comment by berlinux2016** [comment]
fixed & danke
