### ISSUE TITLE
Einstellungen Toggles

### ISSUE THREAD

**Issue by Heinzerunzel** [muhamed89/MIUI#1138]
![screenshot_2017-07-21-10-15-40-817_com android settings](https://user-images.githubusercontent.com/29648253/28455081-0577cb08-6dfe-11e7-874d-69fec9acd0c8.png)

Beim Tippen auf "Bearbeiten" bei den Toggles folgende unübersetzte Zeile:
"14 toggles placed above bar are active"

Mi5S
7.7.20

**Comment by berlinux2016** [comment]
danke & fixed
