### ISSUE TITLE
Taskmanger: Falsche Anzeige/Berechnung vom Arbeitsspeicher 

### ISSUE THREAD

**Issue by reflexxx** [muhamed89/MIUI#160]
Version 5.9.24
Da wird der Gesamt Arbeitsspeicher nicht mehr angezeigt, sondern zweimal der verbleibende.
In der Englischen Sprache ist es richtig! 

![screenshot_com opera browser_2015-09-25-15-39-51](https://cloud.githubusercontent.com/assets/14778731/10103690/a1b49eac-63a5-11e5-9945-caf9869644ec.png)

**Comment by cp82** [comment]
sollte erledigt sein, wird sich nächste woche zeigen
