### ISSUE TITLE
VPN Anzeige doppelt

### ISSUE THREAD

**Issue by reflexxx** [muhamed89/MIUI#162]
Version 5.9.24
VPN Anzeige doppelt, hat aber glaub nix mit der Übersetzung zu tun

![screenshot_com android settings_2015-09-25-15-49-56](https://cloud.githubusercontent.com/assets/14778731/10103949/321cde18-63a7-11e5-9f08-5ef2eef7bebd.png)

**Comment by vivanco-vivanco** [comment]
das liegt an deine einstellung. ich habe das nicht.

**Comment by dahool2016** [comment]
Das ist ein bug von Miui momentan
