### ISSUE TITLE
SSID zeigt standardmäßig Chinesische Zeichen

### ISSUE THREAD

**Issue by reflexxx** [muhamed89/MIUI#166]
Version 5.9.24

kleiner Schönheitsfehler
Standardmäßig wird ein Ch. SSID Name unter "Einstellungen->Mehr->Tethering&Hotspot" angezeigt (siehe Screenshot)
Richtet man den Hotspot ein so kann man die SSID umbennen und die Zeichen sind natürlich weg.
![unbenannt5tsx1](https://cloud.githubusercontent.com/assets/14778731/10104497/41611cb0-63aa-11e5-8511-88e305f4c5a7.jpg)

**Comment by vivanco-vivanco** [comment]
ist behoben !
