### ISSUE TITLE
Telefon/dialer: Übersetzung fehlt

### ISSUE THREAD

**Issue by reflexxx** [muhamed89/MIUI#182]
Version 5.9.24

![unbenannt02uxk](https://cloud.githubusercontent.com/assets/14778731/10116612/79d40afa-6439-11e5-87b9-1af5e1fb1978.jpg)

**Comment by dahool2016** [comment]
Da muss erst einmal die neue settings.apk eingepflegt werden

**Comment by dahool2016** [comment]
Die ersten beiden sind gefixt. Der letzte kommt erst mit dem Update

**Comment by dahool2016** [comment]
alles nun gefixt
