### ISSUE TITLE
Wecker ändern

### ISSUE THREAD

**Issue by vivanco-vivanco** [muhamed89/MIUI#195]

**Comment by vivanco-vivanco** [comment]
![screenshot_com android deskclock_2015-09-25-08-45-17](https://cloud.githubusercontent.com/assets/8560883/10118235/226a2a7a-6474-11e5-84d1-e7d9e92d6a40.png)

**Comment by cp82** [comment]
Hab es schon gekürzt (neuer Wecker). Schaut aber noch immer nicht schön aus.
Wie wär's mit einfach nur "neu" oder "hinzufügen". Ist eh logisch, dass damit ein Wecker gemeint ist.


![screenshot_com android deskclock_2015-09-26-21-40-28](https://cloud.githubusercontent.com/assets/14348503/10119480/4ef55718-6497-11e5-9ab2-35ce99d15c58.png)

**Comment by vivanco-vivanco** [comment]
ja nur hinzufügen :-)
