### ISSUE TITLE
Daten Volumen noch in englisch.

### ISSUE THREAD

**Issue by vivanco-vivanco** [muhamed89/MIUI#198]
![screenshot_com miui home_2015-09-26-16-56-51](https://cloud.githubusercontent.com/assets/8560883/10118271/c45b65d8-6474-11e5-9546-14d60e3c3fab.png)

**Comment by Wackelblume** [comment]
wenn ich wüsste wo das stehen würde....

**Comment by vivanco-vivanco** [comment]
Ich habe auch nicht gefunden. Vllt haben wir die strings. Gelöscht :-/

**Comment by reflexxx** [comment]
neue strings wurden hinzugefügt und bereits übersetzt. Somit Fehler behoben.
