### ISSUE TITLE
Data Saver muss noch übersetzt werden

### ISSUE THREAD

**Issue by cp82** [muhamed89/MIUI#208]
![screenshot_com miui networkassistant_2015-09-26-21-30-22](https://cloud.githubusercontent.com/assets/14348503/10119435/09a0886e-6496-11e5-91b3-e8424e8a37d7.png)

**Comment by cp82** [comment]
Hab schon begonnen. Mache morgen weiter.

**Comment by vivanco-vivanco** [comment]
fehler ist behoben.
