### ISSUE TITLE
Zahlreiche falsche Übersetzungen

### ISSUE THREAD

**Issue by ffw2** [muhamed89/MIUI#283]
![fehler](https://cloud.githubusercontent.com/assets/15077753/10418179/e99b530e-7053-11e5-84f7-0c048dadf1c7.png)

**Comment by ffw2** [comment]
Außerdem funktioniert seit 5.9.24 der Dateimanager nicht mehr.
In addition, file manager does not work since 5.9.24

**Comment by ffw2** [comment]
![fehler_1](https://cloud.githubusercontent.com/assets/15077753/10418353/56cb2964-7058-11e5-8aad-59de3429c3ce.png)

**Comment by reflexxx** [comment]
Bitte erstmal die neuste ROM runterladen 5.10.8 und dann einen Werksreset/wipe machen.
Viele von den gemeldeten Fehler sind schon längst behoben!
