### ISSUE TITLE
german language

### ISSUE THREAD

**Issue by fbrors** [muhamed89/MIUI#296]
auf der Spacetaste bei der Tastatur steht "deutsch" ist das Absicht?

**Comment by reflexxx** [comment]
bei mir nicht. Werksreset durchgeführt? Welches Handy hast du genau?

**Comment by cp82** [comment]
Bei mir auch nicht.
In jeder App oder nur bei einer bestimmten?

**Comment by FireEmerald** [comment]
Das kommt daher, wenn du mehrere Sprachen aktiviert hast. Auf der Spacetaste der Tastatur wird dann immer die aktuell aktive Sprache angezeigt.

**Comment by fbrors** [comment]
Hallo,

 

danke für den Hinweis. Allerdings kann ich mir nicht vorstellen, dass

ich bewusst mehrere Sprachen aktiviert habe. Wo sehe ich das?

Unter Einstellungen/Weiter Einstellungen/Sprache&Eingabe/Sprache/

habe ich nur deutsch aktiviert.

 

Auch unter Einstellungen/Weiter Einstellungen/Sprache&Eingabe/Google-Tastatur/Sprachen/

habe ich nur deutsch aktiviert.

 

 

Gruß

 

F. Brors

 

PS: Kann ich Dir weitere Korrekturvorschläge an diese Email senden?

 

 

 

Von: FireEmerald [mailto:notifications@github.com] 
Gesendet: Samstag, 7. November 2015 19:33
An: muhamed89/MIUI <MIUI@noreply.github.com>
Cc: fbrors <fbrors@arcor.de>
Betreff: Re: [MIUI] german language (#296)

 

Das kommt daher, wenn du mehrere Sprachen aktiviert hast. Auf der Spacetaste der Tastatur wird dann immer die aktuell aktive Sprache angezeigt.

—
Reply to this email directly or view it on GitHub <https://github.com/muhamed89/MIUI/issues/296#issuecomment-154734568> .  <https://github.com/notifications/beacon/AO2Gy8t0PaeeG0QekQGIyudvkReJ_0Jxks5pDjtegaJpZM4GZrur.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by fbrors** [comment]
Korrekturhinweis: 

 

Ort: Weitere Einstellungen/Transfer

Fehler: „Kontekate -> Kontakte“

 

 

Von: FireEmerald [mailto:notifications@github.com] 
Gesendet: Samstag, 7. November 2015 19:33
An: muhamed89/MIUI <MIUI@noreply.github.com>
Cc: fbrors <fbrors@arcor.de>
Betreff: Re: [MIUI] german language (#296)

 

Das kommt daher, wenn du mehrere Sprachen aktiviert hast. Auf der Spacetaste der Tastatur wird dann immer die aktuell aktive Sprache angezeigt.

—
Reply to this email directly or view it on GitHub <https://github.com/muhamed89/MIUI/issues/296#issuecomment-154734568> .  <https://github.com/notifications/beacon/AO2Gy8t0PaeeG0QekQGIyudvkReJ_0Jxks5pDjtegaJpZM4GZrur.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by FireEmerald** [comment]
@fbrors  Einstellungen > Weitere Einstellungen > Sprache & Eingabe > Google-Tastatur > Sprachen

Aber mir ist aufgefallen, selbst wenn du nur eine Sprache aktiviert hast, wird diese einzelne Sprache auf der Tastatur angezeigt. Ergo kein Bug. Achso, wenn du weitere Korrekturvorschläge hast, solltest du evtl. mal hier vorbei schauen: http://xiaomi.eu/community/threads/%C3%9Cbersetzungskorrekturen-miui-v7-deutsch-xiaomi-eu.28411/

Wobei man sich in dem Forum wohl aktuell aus "Spam" gründen nicht mehr registrieren kann...

**Comment by fbrors** [comment]
Soll ich Dir dann Korrekturen zusenden, solange das Forum wg. Spam gesperrt ist?

 

Gruß

 

Florian

 

Von: FireEmerald [mailto:notifications@github.com] 
Gesendet: Montag, 9. November 2015 15:54
An: muhamed89/MIUI <MIUI@noreply.github.com>
Cc: fbrors <fbrors@arcor.de>
Betreff: Re: [MIUI] german language (#296)

 

@fbrors <https://github.com/fbrors>  Einstellungen > Weitere Einstellungen > Sprache & Eingabe > Google-Tastatur > Sprachen

Aber mir ist aufgefallen, selbst wenn du nur eine Sprache aktiviert hast, wird diese einzelne Sprache auf der Tastatur angezeigt. Ergo kein Bug. Achso, wenn du weitere Korrekturvorschläge hast, solltest du evtl. mal hier vorbei schauen: http://xiaomi.eu/community/threads/%C3%9Cbersetzungskorrekturen-miui-v7-deutsch-xiaomi-eu.28411/

Wobei man sich in dem Forum wohl aktuell aus "Spam" gründen nicht mehr registrieren kann...

—
Reply to this email directly or view it on GitHub <https://github.com/muhamed89/MIUI/issues/296#issuecomment-155085276> .  <https://github.com/notifications/beacon/AO2Gy8MfuRs523z3-qI6XZNbOsP0eC2dks5pEKslgaJpZM4GZrur.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by FireEmerald** [comment]
Nein, bitte sende keine Korrekturen an **notifications@github.com**, du bekommst doch nur Benachrichtigungen zu einem Thread auf Github über diese E-Mail Adresse. Schau dir diese Seite an: https://github.com/muhamed89/MIUI/issues/296 dort sind deine ganzen E-Mail Antworten als Posts aufgelistet...

**Comment by FireEmerald** [comment]
@reflexxx Kann geclosed werden, es handelt sich hierbei ja um keinen Fehler.

**Comment by reflexxx** [comment]
done
