### ISSUE TITLE
Galerie > Verstecktes Album anzeigen

### ISSUE THREAD

**Issue by FireEmerald** [muhamed89/MIUI#300]
In der Galerie App in den Einstellungen gibt es die Option (Enable/Disable) "Verstecktes Album anzeigen".

Diese müsste jedoch lauten "Versteckte Alben anzeigen". Beide Strings existieren bereits in [strings.xml#L1070](https://github.com/muhamed89/MIUI/blob/df46551c22219f3f23e0ce4a14b9249380fd5ec8/German/main/MiuiGallery.apk/res/values-de/strings.xml#L1070) bzw. L1069 - hier wird also fälschlicherweise `<string name="show_hidden_album">` verwendet, anstatt `<string name="show_hidden_albums">`.

Die Option blendet mehrere versteckte System Alben ein, anstatt nur ein einzelnes.

**Comment by cp82** [comment]
Danke für die Info!

ich habe mir gerade die englischen Originale angesehen.
Anscheinend gibt es keine Option, ein einzelnes Album zu verstecken...

<string name="show_hidden_albums">Show hidden albums</string>
<string name="show_hidden_album">Show hidden albums</string>

Ich werde den zweiten String auch an die Mehrzahl anpassen.
