### ISSUE TITLE
Missing Translation Strings (Floating notifications)

### ISSUE THREAD

**Issue by FireEmerald** [muhamed89/MIUI#317]
Im Forum ([siehe hier](http://xiaomi.eu/community/threads/%C3%9Cbersetzungskorrekturen-miui-v7-deutsch-xiaomi-eu.28411/page-25#post-261733)) wurden folgende englische Strings gepostet, welche nicht im Github Repository vorhanden sind:

Einstellungen > Benachrichtigungen > Benachrichtigungen anpassen > [Eine App auswählen] >
- "Floating notifications"
- "Floating notifications will disappear automatically after they're shown at the top of the screen"

Btw: @ingbrzy Since some weeks now i try to find a way to register a account on xiaomi.eu/community but the registration on the website and via Tapatalk is disabled - is there any way to register a account?

MIUI-Version: 5.11.12 | Beta

**Comment by FireEmerald** [comment]
Behoben in MIUI-Version: 5.11.19 | Beta

**Comment by ingbrzy** [comment]
@FireEmerald you can register now...

**Comment by FireEmerald** [comment]
@ingbrzy Great - thanks! Registered ;)
