### ISSUE TITLE
Browser.apk: add_ql_bm_title (Add)

### ISSUE THREAD

**Issue by FireEmerald** [muhamed89/MIUI#393]
Browser.apk
```
<string name="add_ql_bm_title">Add</string>
```
Auf Deutsch mit "Hinzufügen" übersetzt, wird dieser String in diesen beiden Szenarien verwendet:
![unbenannt-1](https://cloud.githubusercontent.com/assets/1107939/11452148/a00b2566-95dd-11e5-963a-63b5e0a018a1.jpg)
Mit dem Unterschied, dass der Button in der linken Bildhälfte soviel wie "Fertig" oder "Übernehmen" bedeutet und auf der rechten, die korrekte Bedeutung hat.

Zu links: Man löscht ein paar der angezeigten Links und klickt dann auf "Hinzufügen" um die Änderungen zu übernehmen...

MIUI-Version: 5.11.16 | Beta

**Comment by berlinux2016** [comment]
fixed
