### ISSUE TITLE
Wecker entfernen

### ISSUE THREAD

**Issue by DaDomi** [muhamed89/MIUI#569]
Beim Wecker entfernen steht:
Wecker entfernen

Diesen Wecker entfernen?

Abbruch      Löschen

Entweder man ersetzt das entfernen gegen löschen oder löschen gegen entfernen. Ich würde es gut finden, wenn überall löschen steht. Beim Timer steht auch überall löschen.

MfG

**Comment by berlinux2016** [comment]
Wurde geändert. Merci
