### ISSUE TITLE
Anruf Weiterleitungs Einstellung und QR-Code

### ISSUE THREAD

**Issue by DaDomi** [muhamed89/MIUI#570]
1: Telefon App, Reiter kürzlich oben das Menü öffnen, Einstellungen, Anruf Weiterleitungs Einstellungen. Wenn die Einstellungen gelesen werden, steht darüber "call settings".
2: Kontakte App, länger klick auf einen Kontakt

**Comment by DaDomi** [comment]
Dann auf Anzeigen, runter scrollen auf Mein QR-Code, auf der QR-Code Karte steht "Meinen Informationen" sollte "Meine Informationen" heissen

**Comment by berlinux2016** [comment]
fixed
