### ISSUE TITLE
Fingerprint scan

### ISSUE THREAD

**Issue by marcel21** [muhamed89/MIUI#763]
The Lockscreen and Fingerprint will not Start at Settings.

**Comment by cp82** [comment]
This is no translation issue, it's a MIUI bug

**Comment by ingbrzy** [comment]
it is translation issue.. fixed by https://github.com/muhamed89/MIUI/commit/6622e008f5f08f7bdbf004b35eda183d2f81c585

**Comment by cp82** [comment]
Oh, sorry!
So we should better be more careful with arrays in the future.
