### ISSUE TITLE
Bildbearbeitung/ -hintergrund

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#767]
Hi.. Wenn man in der Gallerie ein Bild öffnet, es bearbeiten will oder als Hintergrund setzen will, fehlt die Übersetzung.

Benutze Redmi 2 TD, MIUI 6.3.10

**Comment by naja66** [comment]
Hier ein Screenshot. K. A. Wie man das hier einbindet.

https://picload.org/image/wwdiapc/screenshot_2016-03-24-09-58-47.png

**Comment by cp82** [comment]
Ist geändert, danke!
