### ISSUE TITLE
Bild löschen Dialog

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#768]
Hi... Wenn man in der Gallerie ein Bild markiert und dieses löschen will kommt ein Dialog auf Englisch.
Die darauf folgende Bestätigung ist ebenfalls auf Englisch.

https://picload.org/image/wwaglci/screenshot_2016-03-24-17-57-27.png

https://picload.org/image/wwaglcw/screenshot_2016-03-24-17-55-14.png

**Comment by FireEmerald** [comment]
Wurde mit Commit https://github.com/muhamed89/MIUI/commit/182db47b9b60fab260c05ae40787240453993aeb behoben.

Siehe https://github.com/muhamed89/MIUI/blame/33fc8f332255e95e6ad949d7bbc3b07ca3d1060f/German/main/MiuiGallery.apk/res/values-de/strings.xml#L293.

**Comment by cp82** [comment]
Hat leider noch gefehlt, hab's gerade hinzugefügt:
https://github.com/muhamed89/MIUI/blob/f759b27b617e49c0b0ede4ae4fe20d3999722aec/German/main/MiuiGallery.apk/res/values-de/plurals.xml#L152
