### ISSUE TITLE
Mi Cloud Einstellungen

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#769]
Hi... Unter Einstellungen -> Systemprogramme -> Mi Cloud ist der unterste Bereich nicht übersetzt. Siehe Screenshot.

https://picload.org/image/wwagpdi/screenshot_2016-03-24-18-39-52.jpg

**Comment by FireEmerald** [comment]
Sollte eigentlich auch bereits behoben sein mit Commit https://github.com/muhamed89/MIUI/commit/e254298f4bbb9158d0dac183672d79dd7707f1d8.

Siehe https://github.com/muhamed89/MIUI/blame/65c4cabdec1d284278b468bcd7b009559d741574/German/main/CloudService.apk/res/values-de/strings.xml#L45

**Comment by naja66** [comment]
Ja, mit dem jetztigen update ist es auf deutsch. Anstatt "Appssichern" sollte eher "Apps sichern" stehen. Supet arbeit was hier geleistet wird. Respekt.

**Comment by Benny1995** [comment]
Habs geändert ;)
