### ISSUE TITLE
Bild löschen Button

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#770]
Hi... Seit dem letzten Update auf 6.3.24 ist der Löschen-Button in der Gallerie verschwunden. Siehe Screenshot.

https://picload.org/image/wwalgwc/screenshot_2016-03-25-11-02-02.jpg

**Comment by cp82** [comment]
Auf meinem Mi 4 ist der Button noch da, aber bei mir sieht die Galerie überhaupt anders aus.
Kannst du vielleicht mal auf Englisch umstellen und nachsehen, ob der Button existiert?

**Comment by naja66** [comment]
Auf englisch und diversen anderen sprachen ist der button da. Wenn man die sprache auf deutsch stellt, verschwindet er.
Benutze ein redmi 2 td

**Comment by cp82** [comment]
Könntest du bitte einen Screenshot auf Englisch posten?
Ich habe den Verdacht, dass die deutschen Texte der anderen Buttons zu lang sind und der letzte Button "rausfällt".

**Comment by naja66** [comment]
https://picload.org/image/wwcrgcp/screenshot_2016-03-28-10-12-12.jpg

**Comment by cp82** [comment]
Danke, ist behoben.
Der Button heißt jetzt wieder "Verbergen", so wie in der alten Version.

**Comment by FireEmerald** [comment]
![screenshot_2016-03-30-11-02-48_com miui gallery](https://cloud.githubusercontent.com/assets/1107939/14137365/cf769318-f667-11e5-9ec5-6727545f4a6e.png)
