### ISSUE TITLE
Bild löschen Dialog Nr 2

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#771]
Hi... Wenn man ein bild in der Gallerie löschen will, kommt ein zur hälfte englischer text. Siehe screenshot

**Comment by naja66** [comment]
<a href="https://picload.org/view/wwpiaar/screenshot_2016-03-30-19-05-04.jpg.html" target="_blank"><img src="https://picload.org/image/wwpiaar/screenshot_2016-03-30-19-05-04.jpg" /></a>

**Comment by cp82** [comment]
Wurde [hier](https://github.com/muhamed89/MIUI/blame/f759b27b617e49c0b0ede4ae4fe20d3999722aec/German/main/MiuiGallery.apk/res/values-de/plurals.xml#L153) behoben
