### ISSUE TITLE
Abbrechen Button in der Bildbearbeitung

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#772]
Hi... Wenn man ein Bild bearbeitet hat und es löschen will, steht oben links zur auswahl "Abbrechen". Dieser button sieht ein wenig verunglückt aus. Siehe screenshot.

Wenn anstelle von "Abbrechen" "Abbruch" stehen würde, wäre das problem wahrscheinlich gelöst.

**Comment by naja66** [comment]
<a href="https://picload.org/view/wwpicdl/screenshot_2016-03-30-19-18-45.jpg.html" target="_blank"><img src="https://picload.org/image/wwpicdl/screenshot_2016-03-30-19-18-45.jpg" /></a>

**Comment by cp82** [comment]
Danke!
Ich versuche, den Wert für die Buttonbreite zu manipulieren.
Falls das nicht klappt, werde ich es in "Abbruch" ändern.

**Comment by cp82** [comment]
Hallo,

es ist mir gelungen, auf meinem Mi 4 die Buttons breiter zu machen.
Hoffe, es klappt auch auf deinem Redmi 2. Dort scheint eine andere Schriftart eingestellt zu sein, ich hatte das Problem mit dem Zeilenumbruch gar nicht.

Vorher:
![vorher](https://cloud.githubusercontent.com/assets/14348503/14168097/3433027e-f720-11e5-9d32-f74276c42af2.png)

Nachher:
![nachher](https://cloud.githubusercontent.com/assets/14348503/14168096/34228084-f720-11e5-918a-f248a3519a9d.png)

**Comment by naja66** [comment]
Ok... Ja so müsste es klappen. Werde nachdem update feedback geben.

**Comment by naja66** [comment]
Fehler wurde behoben. Super arbeit

**Comment by naja66** [comment]
Hi...
Der abbrechen text ist in hellgrau. Der speichern text ist in weiß.

Ist das so gewollt?

**Comment by cp82** [comment]
Ja.
Sobald du was änderst, wird auch der "Speichern" Button weiß ;-)
