### ISSUE TITLE
Mi Nachrichten Erklärung

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#775]
Wenn man unter Einstellungen -> Systemprogramme -> SMS/ MMS geht, steht die Mi Nachrichten erklärung auf Englisch. Siehe Screenshot.

<img src="https://picload.org/image/rggrocgr/screenshot_2016-04-01-23-23-25.jpg" /></a>

**Comment by cp82** [comment]
Ist geändert, danke!
