### ISSUE TITLE
Anwendungssperre unvollständiger Text

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#778]
Hi... Auf meinem Redmi 2 TD (MIUI 6.3.31) wird bei der Sicherheit App -> Anwendungssperre dir Erklärung nicht vollständig gezeigt. Kann man das ganze auf 2 Zeilen verteilen? Siehe Screenshot.

<img src="https://picload.org/image/rggiwrai/screenshot_2016-04-08-19-28-32.jpg" /></a>

**Comment by naja66** [comment]
P. S. Der Abstand zu den Rändern ist mMn designtechnisch zu gering

**Comment by cp82** [comment]
Ich hab den Text durch einen kürzeren ersetzt:
"Sichern Sie den Zugriff auf Ihre Apps"

Sollte sich also ausgehen.

Was den Abstand angeht, der Text sollte eigentlich zentriert angezeigt werden.

**Comment by cp82** [comment]
![screenshot_2016-04-15-09-59-23_com miui securitycenter](https://cloud.githubusercontent.com/assets/14348503/14555099/d9b6b818-02f0-11e6-8ef8-8f3ae0498f16.png)
