### ISSUE TITLE
Rufnummeranzeige

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#783]
Hi... Unter Einstellungen -> Anrufeinstellungen -> Rufnummernanzeige -> "Nummer bei abgehenden Anrufen "angezeigt". 

Sollte besser in "anzeigen" geändert werden. Siehe Screenshot.

<img src="https://picload.org/image/rgrrlwpi/screenshot_2016-04-12-08-29-09.jpg" /></a>

**Comment by berlinux2016** [comment]
Fixed. danke!
