### ISSUE TITLE
Musikeinstellungen

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#791]

**Comment by naja66** [comment]
Hi. Unter Einstellungen -> Systemprogramme -> Musik ist zum einen die Seite falsch betitelt und zum anderen falsch formatiert (Komma, Abzkürzung und Groß-/ Kleinschreibung). Siehe Screenshot.

<img src="https://picload.org/image/rgrddrrr/screenshot_2016-04-12-18-49-06.jpg" />

**Comment by cp82** [comment]
Der Text lautet auf Englisch auch "Service and Settings".
Wahrscheinlich sind hier Dienste gemeint. In China hat dieses Menü vielleicht noch mehrere Einträge.

Aber nachdem ich keine Dienste entdecken kann, benenne ich es mal um in "Einstellungen".

**Comment by naja66** [comment]
Ah ok. Denn in allen anderen Seitentiteln ist der jeweilige Menüname benutzt worden... Kalender -> Kalender, Notizen -> Notizen, usw.
Aber so passts auch ;)
