### ISSUE TITLE
Jugendschutz?

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#808]
Unter Einstellungen ist der Punkt Jugendschutz vorhanden. Ist das nicht eher ein Kinderschutz bzw. -modus? Auf englisch heißt es child mode. Siehe Screenshot.

<img src="https://picload.org/image/rgrpaowg/screenshot_2016-04-18-09-57-08.jpg" /></a>

**Comment by berlinux2016** [comment]
Kindersicherung? Wie bei ios?

**Comment by naja66** [comment]
Würde ebenfalls gehen

**Comment by berlinux2016** [comment]
Ist in der ROM ab 22.04. geändert
