### ISSUE TITLE
Datei unbenennen

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#818]
Hi... Bei der Umbenennung einer Datei im Dateimanager wird als Infodialog "Ordner unbenennen" angezeigt. Sollte "Datei unbenennen" heißen. Siehe Screenshot.

<img src="https://picload.org/image/rgdddwdo/screenshot_2016-04-21-22-21-26.jpg" />

**Comment by naja66** [comment]
<img src="https://picload.org/image/rgdddwdo/screenshot_2016-04-21-22-21-26.jpg" />

**Comment by naja66** [comment]
Zweitens: Wenn man längere Dateinamen markiert, erscheint ja die Auswahl "Alles, Ausschneiden, Kopieren, Einfügen". Die letzte Auswahl (Einfügen) verteilt sich auf zwei Zeilen und es kommt zu einem Schönheitsfehler. Screenshot ist nicht möglich.

**Comment by cp82** [comment]
1) auf Englisch steht dort auch "Rename Folder", es gibt keinen String für Datei umbenennen.
Wir könnten schreiben "Element umbenennen", "Datei oder Ordner umbenennen" oder "Auswahl umbenennen".

2) Bei mir geht sich's locker aus, hast du eine größere Schrift eingestellt?
![screenshot_2016-04-22-06-32-52_com android fileexplorer](https://cloud.githubusercontent.com/assets/14348503/14731764/560bc3e6-0854-11e6-85a4-32e9ad1482f7.png)

**Comment by naja66** [comment]
Hi.. Auswahl unbenennen macht mMn am meisten Sinn.

Zu 2: Habe Schriftgröße S. Screenshot jetzt gemacht.

<img src="https://picload.org/image/rgddpoii/screenshot_2016-04-22-16-06-46.jpg" />

**Comment by FireEmerald** [comment]
Ähnliche "Zeilenumbrüche" sind mir auch schon des öfteren aufgefallen, ich glaube aber, dass wir an diesem Punkt durch reine Übersetzungen nicht viel ändern können.

**Comment by cp82** [comment]
Manchmal lässt sich schon was machen, schau mal hier: #772 
Ich habe mittels einem eigenen dimens.xml File für Deutsch die Buttonbreite verändert.

Aber hier haben wir leider kein Glück. Der Text auf dem Redmi 2 wirkt größer als auf meinem Mi4. Die dimens.xml Files sind aber für beide Devices identisch, das habe ich mir angeschaut.

Aber "Ausschneiden" abkürzen auf etwa "Ausschn." finde ich auch nicht besonders schön.
Ich würde es gerne so belassen.

Der erste Punkt ist übrigens erledigt. Umbenannt in "Auswahl umbenennen".

**Comment by naja66** [comment]
OK ;)
