### ISSUE TITLE
Galerie Album slimming

### ISSUE THREAD

**Issue by FireEmerald** [muhamed89/MIUI#831]
In der Gallery auf meinem MiNotePro: **(6.4.14)**
![screenshot_2016-04-22-23-50-30_com miui gallery_1461361866969](https://cloud.githubusercontent.com/assets/1107939/14755826/311093fa-08e5-11e6-8935-d290ab7970c2.jpg)

Der Text ließt sich nicht sonderlich gut und wenn man auf diesen einen Click ausführt, gelangt man auf folgenden Screen:

![screenshot_2016-04-22-21-53-21_com miui gallery](https://cloud.githubusercontent.com/assets/1107939/14755779/eca1c54a-08e4-11e6-8548-e2f85bf40d96.png)

**Comment by cp82** [comment]
Wurde schon behoben, sollte in 6.4.21 schon passen:
https://github.com/muhamed89/MIUI/commit/5103c503d54c221514ac2259027b2f1984f3b557
und
990e072daaa4afa4542798b9036a00c20277d5eb
