### ISSUE TITLE
Unnötige Satzpunkte

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#842]
Hi... Unter Einstellungen -> Weitere Einstellungen -> Sichern & Widerherstellen -> Auf Werkszustand zurücksetzen sind jeweils zwei Satzpunkte die nicht gebraucht werden. Siehe Screenshot.

<img src="https://picload.org/image/rgdcgrac/screenshot_2016-04-25-17-33-53.jpg" />

**Comment by cp82** [comment]
Ist korrigiert, danke!
