### ISSUE TITLE
Falsche Bezeichnung

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#867]
Hi... Unter Einstellungen -> Bildschirmsperre & Passwort -> Sperrbildschirm steht Jugendschutz. Sollte hier nicht Kindersicherung stehen? Siehe Screenshot.

<img src="https://picload.org/image/rgdplwao/screenshot_2016-04-27-16-45-43.jpg" />

**Comment by naja66** [comment]
"ERFORDERN ENTSPERREN" ?

**Comment by cp82** [comment]
Alle kortigiert, danke!
