### ISSUE TITLE
Tägliche Hintergrundbilder

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#869]
Hi.. Unter Einstellungen -> Hintergrund -> Hintergrund auswählen -> Tägliche Hintergrundbilder festlegen ist mir folgendes aufgefallen. Siehe Screenshots.

<img src="https://picload.org/image/rgdwcdwc/screenshot_2016-04-28-05-57-11.jpg" />

<img src="https://picload.org/image/rgdwcadi/screenshot_2016-04-28-05-57-27.jpg" />

**Comment by cp82** [comment]
Sollte schon behoben sein.
Ob die gekürzten Texte jetzt passen, werden wir in 6.4.28 sehen.

**Comment by naja66** [comment]
Jetzt ist alles bestens. Super Arbeit!
