### ISSUE TITLE
Mi Cloud Speicherstatus

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#875]
Hi... Unter Einstellungen -> Mi Konto ->  Mi Cloud -> Speicher ist die Seite nicht übersetzt. Siehe Screenshot.

<img src="https://picload.org/image/rgagpdpd/screenshot_2016-04-29-20-16-32.jpg" />

**Comment by cp82** [comment]
Hmmm, konnte es leider bisher nicht finden.
Ich bleibe aber dran.

**Comment by cp82** [comment]
Ich hab's gefunden. Ist aber leider im Source Code, lässt sich also nicht übersetzen.
