### ISSUE TITLE
Geburtstag-Benachrichtigung

### ISSUE THREAD

**Issue by bReathl3sS** [muhamed89/MIUI#891]
Weiß leider nicht, wie ich den korrigieren kann.
3 Tage vor Geburtstag kam folgende Meldung als Benachrichtigung von Kalender:
"KONTAKNAME's Geburtstag Tage später."
Sollte wohl eigentlich lauten
"KONTAKNAME's Geburtstag in 3 Tagen."

vorraussichtlich:
Datei: MIUI/German/main/Calendar.apk/res/values-de/strings.xml
Zeile 77: "%1$s's %2$s Tage später."

Müsste wohl irgendwie "%1$s's %2$s in XY Tagen." werden. Mit XY als Variable

**Comment by cp82** [comment]
Sollte jetzt passen, hab's generell umformuliert
X hat in y Tagen Geburtstag
X hat heute/morgen/übermorgen Geburtstag

**Comment by bReathl3sS** [comment]
Perfekt
