### ISSUE TITLE
Mi Konto Schreibfehler

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#908]
Hi... Unter Einstellungen -> Mi Konto -> Konten steht unter Facebook "Hinzugefügt". Sollte hier nicht besser "Hinzufügen" stehen? Siehe Screenshot.

<img src="https://picload.org/image/rgolgdaw/screenshot_2016-05-12-09-42-11.jpg" />

**Comment by naja66** [comment]
Und "Facebookonto" wird auseinander geschrieben. Siehe Screenshot.

<img src="https://picload.org/image/rgolgdid/screenshot_2016-05-12-09-44-44.jpg" />

**Comment by cp82** [comment]
Wenn kein Konto hinzugefügt ist, steht "Nicht verbunden".

Der Text "Hinzugefügt" steht, wenn eines verbunden ist. Habe es in "Verbunden" geändert, auf Englisch steht auch "Connected".
