### ISSUE TITLE
Ausgehende Anrufe

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#924]
Hi... Unter Einstellungen -> Systemanwendungen -> Telefon -> Rufnummernanzeige -> Nummer anzeigen steht "... bei abgehenden Anrufen...". Hier sollte "ausgehenden" stehen. Siehe Screenshot.

<img src="https://picload.org/image/rgcroopo/screenshot_2016-05-22-20-19-17.jpg" />

**Comment by bReathl3sS** [comment]
Done
