### ISSUE TITLE
Textdialog

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#925]
Hi... Wenn man eine Nachricht schreibt und etwas einfügen will kommt ein englischer Auswahlbutton. Siehe Screenshot.

<img src="https://picload.org/image/rgcrolrw/screenshot_2016-05-22-20-26-29.jpg" />

**Comment by bReathl3sS** [comment]
Ist meines Wissens nach bereits übersetzt, nur nicht im aktuellen Build drin ;) #

**Comment by cp82** [comment]
Ja, ist mir heute schon untergekommen: "Häufig verwendete Sätze"
Ich hoffe, das geht sich von der Breite her aus.
