### ISSUE TITLE
Berührungsassistent

### ISSUE THREAD

**Issue by naja66** [muhamed89/MIUI#928]
Hi.. Ist wahrscheinlich schon bekannt. Unter Einstellungen -> Weitere Einstellungen -> Berührüngsassistent ist die Seite nicht übersetzt. Siehe Screenshot.

<img src="https://picload.org/image/rgcrocgr/screenshot_2016-05-22-20-31-16.jpg" />

**Comment by bReathl3sS** [comment]
Wurde übersetzt, der Commit war leider nur zu spät :-)
