### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by gejoka1234** [muhamed89/MIUI#937]
Ich habe ein Xiaomi Redmi Note 2.
MIUI Version 7.4 by xiaomi.eu 6.5.5 Beta.
Seit dem letzten up date bekomme ich des öfteren amTage die Meldung "Rooming scheint aktiv zu sein"
Ich habe Rooming auf "aus" stehen.
Dies scheint ein bug zu sein. Kann sich ein Experte das mal anschauen.
Des weitern habe ich die Frage, ob man die Empfangsleistung des "mobilen Datenempfangs" softwaremäßig anpassen kann. Meine Frau hat ein Redmi 2 und kann unseren Provider auch dann empfangen, wenn das Provider Signal relativ schwach ist. Ich mit meinem Redmi Note 2 habe keinen Empfang.
Kann sich das auch mal jemand ansehen.
Danke.

**Comment by Bomberus** [comment]
Wende dich an das xiaomi.eu Forum. In diesem Repository sind nur die Übersetzungen gespeichert.
