### ISSUE TITLE
Einrichtung MIUI 8

### ISSUE THREAD

**Issue by bReathl3sS** [muhamed89/MIUI#947]
Bing erade mein RN2 auf MIUI 8 am umstellen, dabei stelle ich fest, dass "Weiter" übersetzt ist, jedoch statt Zurück und Überspringen noch Skip und Back stehen (zB beim Erstmaligen Verbinden mit dem WiFi.
Bei den Nutzungsbedingungen steht als Ankreuzhäkchen noch "I've read and agree to the Terms of Service and Privacy Policy"
Außerdem "Choose a theme" ist komplett englisch.
Am Ende kommt dann noch "Setup complete"

**Comment by cp82** [comment]
fixed
