### ISSUE TITLE
Chinesische Meldung und Button im Browser

### ISSUE THREAD

**Issue by z4nith** [muhamed89/MIUI#949]
Betrifft: MIUI v8 6.6.23

Von der Startseite des Browser ein mal nach rechts wischen (hier bei vielen Tabs erscheint unten chinesischer Text)

![screenshot_2016-06-27-14-00-30-679_com android browser](https://cloud.githubusercontent.com/assets/20169882/16385353/bde96c0e-3c8c-11e6-8160-fcacadc04468.png)
![screenshot_2016-06-27-14-01-19-027_com android browser](https://cloud.githubusercontent.com/assets/20169882/16385352/bde7f9a0-3c8c-11e6-9f53-d497a043ae3d.png)

**Comment by cp82** [comment]
Bisher konnte ich nichts finden.
Ich fürchte, das wird aus dem Web geladen.

**Comment by vivanco-vivanco** [comment]
Bei mir ist alles in Englisch, wir können daran nicht machen weil, das von web geladen wird.

Können wir issues von z4nith löschen ?

**Comment by z4nith** [comment]
Zur Info - auch ich sehe jetzt an der Stelle englische Texte...
