### ISSUE TITLE
Akkuverbrauch optimieren

### ISSUE THREAD

**Issue by mouzzza** [muhamed89/MIUI#950]
In der App "Sicherheit" findet man unter Akku->Akkuverbrauch analysieren den Button "abkühlen".
Dieser sollte "optimieren" heißen?! 
`184   <string name="btn_text_quick_save_power">Abkühlen</string> `

**Comment by vivanco-vivanco** [comment]
vielen dank, wir haben es in "optimieren"  benannt.

**Comment by cp82** [comment]
Auf Englisch steht Cool Down, die Meldung kommt in Verbindung mit der Überhitzungswarnung.
Aber "Optimieren" klingt trotzdem besser 👍

**Comment by mouzzza** [comment]
Cool down wird eher als "Komm runter" verstanden und ist somit in Bezug zu Temperatur und Ausdauer äußerst passend!

Jedenfalls danke für die Berücksichtigung.
