### ISSUE TITLE
Zweitprofil Private Nachrichten

### ISSUE THREAD

**Issue by dopephish** [muhamed89/MIUI#971]
Wenn man im Zweitprofil auf Verwalten klickt unter "Private Nachrichten anzeigen": Hier ist ein Fehler -> Statt "Aus" müsste "Ein" stehen und umgekehrt. 
Auch wenn man auf "Private Nachrichten anzeigen" klickt, kommt man zu "Private Nachrichten im Zweitprofil anzeigen um sie jederzeit zu erhalten". Darunter ist ein Button "Einschalten" - > betätigt man diesen, wird die Funktion aber ausgeschaltet. Danach erscheint bei mir "Private messages are shown in Second space" "Messaging data will be shared between two spaces". Darunter ist wieder ein Button "Private Daten nicht anzeigen" -> müsste aber "Private Daten anzeigen" heißen.
Kompliziert zu erklären - eigentlich passiert aber genau das Gegenteil von dem was man möchte. Die Übersetzung müsste einfach nur ins Gegenteil umgekehrt werden.

  
            
 
Write

**Comment by dopephish** [comment]
Wenn man im Zweitprofil auf Verwalten klickt unter "Private Nachrichten anzeigen": Hier ist ein Fehler -> Statt "Aus" müsste "Ein" stehen und umgekehrt. 
Auch wenn man auf "Private Nachrichten anzeigen" klickt, kommt man zu "Private Nachrichten im Zweitprofil anzeigen um sie jederzeit zu erhalten". Darunter ist ein Button "Einschalten" - > betätigt man diesen, wird die Funktion aber ausgeschaltet. Danach erscheint bei mir "Private messages are shown in Second space" "Messaging data will be shared between two spaces". Darunter ist wieder ein Button "Private Daten nicht anzeigen" -> müsste aber "Private Daten anzeigen" heißen.
Kompliziert zu erklären - eigentlich passiert aber genau das Gegenteil von dem was man möchte. Die Übersetzung müsste einfach nur ins Gegenteil umgekehrt werden.

**Comment by berlinux2016** [comment]
Teil gefixed. Teil wird noch angesehen.
