### ISSUE TITLE
Kamera

### ISSUE THREAD

**Issue by jonnyzocker** [muhamed89/MIUI#982]
Kamera kann nicht immer Verbindung aufbauen mit der App

-Kamera kann keine Verbindung auf bauen 
Gerade bei Snapchat geht's nicht.
Hab Handy öfters neugestartet die Vorversion der Rom funktionierte es noch.

**Comment by berlinux2016** [comment]
welche Version und welches Gerät?

**Comment by jonnyzocker** [comment]
Redmi 3S 
Version 6.8.18 Xiaomi.eu

**Comment by berlinux2016** [comment]
Nachmal bitte testen mit der neuen ROM

**Comment by jonnyzocker** [comment]
Leider besteht das Problem immer noch:(

**Comment by berlinux2016** [comment]
kannst du nochmal genauer dein problem schildern. Ich kann es hier leider nicht reproduzieren worin das Problem genau liegt. Snapchat (auch mit Fotos) läuft hier ohne Probleme.

**Comment by jonnyzocker** [comment]
Wenn ich zwischen Kamera Apps Wechsel und sie dann beende und eine neue starte kommt das

**Comment by berlinux2016** [comment]
Du hast mehrere Kamera Apps? Welche? Google Kamera?
