### ISSUE TITLE
Lock screen & password

### ISSUE THREAD

**Issue by HirschiD** [muhamed89/MIUI#993]
Wird in diesem Menü ein Pin oder Muster gesetzt kann es danach nicht mehr aufgerufen werden. Bzw bei jedem Aufruf geht es nach ein paar Sekunden wieder zurück in das Einstellungs-Menü.

**Comment by cp82** [comment]
Kann ich auf dem Mi4 nicht bestätigen.
Ich kann die Sperre beliebig ändern und auch wieder entfernen.

Welches Device hast du?

**Comment by HirschiD** [comment]
Redmi 3 Pro

Am 13.09.2016 7:31 vorm. schrieb "cpu82" <notifications@github.com>:

**Comment by HirschiD** [comment]
Android-Version: 5.1.1 LMY47V
MIUI-Version: MIUI Global 7.3 | Stable
                       7.3.5.0(LHPCDB)

**Comment by berlinux2016** [comment]
Bitte die Dev Version nutzen. In der Global Stable ist ein bug drin.

**Comment by HirschiD** [comment]
Wie bekomme ich die? Hab jetzt ein paar versionen runtergeladen, entweder ist der fehler nicht behoben oder die rom lässt sich nicht installieren "Can't verify update"
